### PR TITLE
fix: do not depend by default on `async-std`

### LINKED ISSUE #303: `async-std` has been deprecated; emitted async tests should run on `smol`
The `async-std` project [has been deprecated](https://github.com/async-rs/async-std/blob/fb56bff/README.md#async-std-has-been-discontinued-use-smol-instead) and the official recommendation is to use `smol` instead.

Currently it appears to be impossible to use `smol`'s test attribute because [it doesn't end with `test`](https://docs.rs/smol-macros/latest/smol_macros/macro.test.html#examples). Instead, it looks like `#[macro_rules_attribute::apply(smol_macros::test!)]`. This is a challenge given the existing mechanisms for [injecting test attributes](https://docs.rs/rstest/latest/rstest/attr.rstest.html#inject-test-attribute), which is neatly avoided by making `smol` tests the default.

### PR DESCRIPTION
**Pull request by coriolinus**
Closes #303.

### CODE REVIEW

File: rstest_macros/src/render/mod.rs [hunk 1]
```diff
@@ -200,19 +203,32 @@ pub(crate) fn matrix(mut test: ItemFn, mut info: RsTestInfo) -> TokenStream {
...
+    if !is_async {
+        Ok(Some(quote! { #[test] }))
+    } else if let Some(explicit_attr) = explicit_test_attr {
+        Ok(Some(explicit_attr))
+    } else if attributes
+        .iter()
+        .any(|attr| attr_ends_with(attr, &parse_quote! {test}))
+    {
+        // test attr is already in the attributes; we don't need to re-inject it
+        Ok(None)
```
Comment (la10736) [inline rstest_macros/src/render/mod.rs:229]: There is something wrong in this logic: It doesn't work if you want to use a custom test attribute for a not async test.

I'm wondered that there isn't any test that catch it :cry:

File: rstest_macros/src/render/mod.rs [hunk 2]
```diff
@@ -200,19 +203,32 @@ pub(crate) fn matrix(mut test: ItemFn, mut info: RsTestInfo) -> TokenStream {
...
     } else {
-        quote! { #[test] }
+        Err(syn::Error::new(error_span, "async tests require either an explicit `test_attr` or an attribute whose path ends with `test`"))
```
Comment (la10736) [inline rstest_macros/src/render/mod.rs:231]: You can use a `compiler_error!` macro instead : you're in the rendering stage so it's legit to use it to inform the user.

Anyway, maybe the best thing is to inspect the data after parsing and catch the case where the mandatory test attribute is missed.

File: rstest_macros/src/render/mod.rs (hunk 1 above)
Comment (coriolinus) [reply rstest_macros/src/render/mod.rs:229]: Good point on the logic.

I haven't started working on testing this yet; I'll add a relevant case.

File: rstest_macros/src/render/mod.rs (hunk 2 above)
Comment (la10736) [reply rstest_macros/src/render/mod.rs:231]: Yeah, I know the difference, this is way I prefer to catch all errors in parsing stage or by inspecting the parsed output to check coherence.  Take a look to `error::rstest` to see how all other cases are handled.

**Comment by coriolinus** [comment]
I need to add some tests but I think the core functionality here is in a relatively good state. Please let me know if you have any comments.

**Comment by coriolinus** [comment]
I now believe this to be ready for review. Looking forward to your comments @la10736 !

**Comment by coriolinus** [comment]
@la10736 I've been working on this PR and at this point all test cases pass on my machine. Hopefully CI agrees!

With regard to https://github.com/la10736/rstest/pull/311/commits/b5bf8e0755dee110db2f56edc035ff696ea52f74, I don't love this limitation, but I don't see a way around it. I don't understand the attribute-parsing machinery well enough to improve on the situation. I do feel it's important to point out that this is not a new limitation introduced by this PR; it's just much more obvious now that every async case requires an explicit or implicit test attribute.

**Comment by coriolinus** [comment]
I'm looking at `fn extract_global_awt`, and the traits associated with `GlobalAwtBuilder`, and I'm coming to the conclusion that this is more complicated than I'd really like to deal with, for now at least. For my use case, it's acceptable to manually ensure that all cases come before the test attribute.

Are you willing to accept the PR in its current state, assuming that CI goes green?

**Comment by la10736** [comment]
In my last comment I forgot to mention that `extract_global_awt`'s code and how it's used is a simple example of how parse and rid of function attributes that should be present at most once.

**Comment by coriolinus** [comment]
Thank you!
